"""tests/test_make_bundle.py — scripts/lana/make_bundle.py."""
from __future__ import annotations

import json
import zipfile

from conftest import SCRIPTS, run


def run_make_bundle(proj):
    return run(SCRIPTS / "lana" / "make_bundle.py", [], cwd=proj, env={"REEL_PROJECT": str(proj)})


def seed(project_dir):
    """D17: make_bundle.py no longer reads lana-pkg/props.json at all — the
    bundled props.json is always a hardcoded {}, since the plan now travels
    inside lana-pkg/src/*.ts (plan.ts/ritmo.ts/gfx.ts, generated by
    make_pkg.py, D17 v2) instead of as lana_submit_render's `props`."""
    src = project_dir / "lana-pkg" / "src"
    src.mkdir(parents=True, exist_ok=True)
    (src / "Root.tsx").write_text("export const x = 1;\n", encoding="utf-8")
    (src / "plan.ts").write_text(
        'import type { Plan } from "./types";\nexport default ({}) as unknown as Plan;\n', encoding="utf-8",
    )


def test_deterministic_sha_across_two_runs(project_dir):
    seed(project_dir)
    r1 = run_make_bundle(project_dir)
    assert r1.returncode == 0, r1.stderr
    sha1 = (project_dir / "lana-pkg" / "bundle.sha256").read_text().strip()

    r2 = run_make_bundle(project_dir)
    assert r2.returncode == 0, r2.stderr
    sha2 = (project_dir / "lana-pkg" / "bundle.sha256").read_text().strip()

    assert sha1 == sha2

    project = json.loads((project_dir / "project.json").read_text())
    assert project["assets"]["bundle"]["sha256"] == sha1


def test_forbidden_extension_exits_1(project_dir):
    src = project_dir / "lana-pkg" / "src"
    src.mkdir(parents=True, exist_ok=True)
    (src / "notallowed.exe").write_bytes(b"binary")
    result = run_make_bundle(project_dir)
    assert result.returncode == 1
    assert ".exe" in result.stderr
    assert not (project_dir / "lana-pkg" / "bundle.zip").exists()


def test_bundled_props_json_is_always_empty_object(project_dir):
    """D17's actual fix, tested directly against the zip contents: whatever
    build.py/make_pkg.py did or didn't write anywhere, the bundle's own
    props.json entry is always exactly {}."""
    seed(project_dir)
    result = run_make_bundle(project_dir)
    assert result.returncode == 0, result.stderr
    with zipfile.ZipFile(project_dir / "lana-pkg" / "bundle.zip") as zf:
        assert zf.read("props.json") == b"{}"


def test_code_over_256kib_exits_1(project_dir):
    """D17 v2: RENDER_MAX_CODE_BYTES applies to CODE only
    (.ts/.tsx/.js/.jsx) — since D17 v2 this INCLUDES plan.ts/ritmo.ts/
    gfx.ts (it never did as .json — the whole reason they moved to .ts
    was that the gateway can't resolve a .json import in the first place)."""
    src = project_dir / "lana-pkg" / "src"
    src.mkdir(parents=True, exist_ok=True)
    (src / "plan.ts").write_text(
        'import type { Plan } from "./types";\nexport default ({}) as unknown as Plan;\n', encoding="utf-8",
    )
    (src / "Big.tsx").write_text("export const x = " + repr("x" * (300 * 1024)) + ";\n", encoding="utf-8")
    result = run_make_bundle(project_dir)
    assert result.returncode == 1
    assert "RENDER_MAX_CODE_BYTES" in result.stderr


def test_plan_ts_counts_against_code_limit(project_dir):
    """D17 v2 reversal of the old D17-v1 test: a large plan.ts (the plan
    now travels as a .ts module, not .json) DOES trip the code-size gate —
    the exact reason make_pkg.py breaks down and fails on this before a
    submit, and the mirror of why .json never worked as an import target in
    the first place."""
    src = project_dir / "lana-pkg" / "src"
    src.mkdir(parents=True, exist_ok=True)
    (src / "Root.tsx").write_text("export const x = 1;\n", encoding="utf-8")
    payload = json.dumps({"pad": "x" * (300 * 1024)}, separators=(",", ":"))
    (src / "plan.ts").write_text(
        f'import type {{ Plan }} from "./types";\nexport default ({payload}) as unknown as Plan;\n',
        encoding="utf-8",
    )
    result = run_make_bundle(project_dir)
    assert result.returncode == 1
    assert "RENDER_MAX_CODE_BYTES" in result.stderr


def test_json_under_src_exits_1(project_dir):
    """D17 v2 defense-in-depth guard: a stray .json under lana-pkg/src/
    (e.g. a leftover from an older make_pkg.py run) is rejected rather than
    silently zipped — make_pkg.py should never produce one, but this is the
    backstop if it (or a hand-edit) ever does."""
    src = project_dir / "lana-pkg" / "src"
    src.mkdir(parents=True, exist_ok=True)
    (src / "Root.tsx").write_text("export const x = 1;\n", encoding="utf-8")
    (src / "plan.json").write_text("{}", encoding="utf-8")
    result = run_make_bundle(project_dir)
    assert result.returncode == 1
    assert "plan.json" in result.stderr
    assert "stale" in result.stderr


def test_content_change_invalidates_asset_id(project_dir):
    seed(project_dir)
    run_make_bundle(project_dir)
    project = json.loads((project_dir / "project.json").read_text())
    project["assets"]["bundle"]["asset_id"] = "00000000-0000-4000-8000-000000000077"
    (project_dir / "project.json").write_text(json.dumps(project), encoding="utf-8")

    (project_dir / "lana-pkg" / "src" / "Root.tsx").write_text("export const x = 2;\n", encoding="utf-8")
    run_make_bundle(project_dir)
    updated = json.loads((project_dir / "project.json").read_text())
    assert updated["assets"]["bundle"]["asset_id"] is None


def test_missing_src_exits_2(project_dir):
    result = run_make_bundle(project_dir)
    assert result.returncode == 2
