// PLACEHOLDER — regenerated by make_pkg.py from project.json before every
// bundle: one entry per REGISTERED asset (asset_id set, status ready,
// purpose != bundle), keyed by its project.assets key, value already a
// staticFile(...) call over the literal "assets/<key>.<ext>" the Lana
// gateway validates the submit's `assets` map against — the map must come
// from the registry and the literal must be visible to the gateway, or
// nothing gets staged and the render comes back black. Never edit this
// file by hand.
//
// This is a type contract, not just a stub: make_pkg.py emits the exact
// same `export const ASSET_FILES: Record<string, string> = { ... };`
// annotation — never `as const`, never inferred — so a real project
// typechecks against the same shape this placeholder gives `npm run check`.
import { staticFile } from "remotion";

export const ASSET_FILES: Record<string, string> = {};

void staticFile;
