// PLACEHOLDER — regenerated by make_pkg.py from project.fonts.custom (and
// any shared-library font, kind=font, picked in the questionnaire) before
// every bundle. `file` is already a staticFile(...) result, over either
// "assets/<key>.ttf" (a user's own upload) or "lib/<id>.<ext>" (a shared-
// library font — same literal-only rule as library-manifest.ts: the
// gateway only ever stages a lib/ file it can see as a literal). Never
// edit this file by hand. A project with no file fonts renders fine
// against this empty manifest (Fonts.tsx skips the @font-face injection
// when it's empty).
//
// Type contract: make_pkg.py emits the exact same
// `export const FONT_FILES: Record<string, FontFile> = { ... };`
// annotation this placeholder gives `npm run check`.
import type { FontFile } from "./types";

export const FONT_FILES: Record<string, FontFile> = {};
