// Single resolver for every file the render references.
//
// The Lana render gateway derives what it stages ONLY from what it can
// see. For `assets/` it validates the submit's registered-asset map
// against literal staticFile("assets/<key>.<ext>") calls; for `lib/`
// those literals are the ONLY source it reads at all — a variable
// reference is invisible to it and never gets staged. (A submit whose
// asset map came from scanning code for literals, while this resolver
// looked everything up by variable, once rendered every real reel as a
// silent black frame: the map was always empty and the harness had
// nothing to stage.)
// staticFile with a LITERAL now lives only in the generated manifests
// (assets-manifest.ts, library-manifest.ts, fonts-manifest.ts) — this file
// never calls staticFile with a variable for "assets/" or "lib/". `sfx/` is
// the one exception: the harness stages the whole pack on every job, so a
// variable reference there is safe (and is how Sfx.tsx uses it).
import React from "react";
import { Img, staticFile } from "remotion";
import { Video } from "@remotion/media";
// Generated by make_pkg.py from project.json before every bundle. Every
// value here is ALREADY a staticFile(...) result — resolve by lookup only.
import { ASSET_FILES } from "./assets-manifest";
import { LIB_FILES } from "./library-manifest";

export const asset = (name: string): string => {
  if (name.startsWith("sfx/")) return staticFile(name);   // Lana SFX pack: staged whole per job, variable is fine
  if (name.startsWith("lib/")) {
    const l = LIB_FILES[name];
    if (!l) throw new Error(`library file "${name}" is not in project.json library.items`);
    return l;
  }
  const f = ASSET_FILES[name];
  if (!f) throw new Error(`asset "${name}" is not registered in project.json`);
  return f;
};

// A registered asset can be a still image or a muted video (screenshots and
// card art can come from either — prep_upload.py adds a silent audio track
// to any mp4/mov that lacks one, so ingest never rejects it). React.createElement,
// not JSX: this file stays a plain .ts module. make_pkg.py's literal-usage
// check only allows a non-literal staticFile call in this file and in
// Sfx.tsx — keeping a .tsx twin of this file would split that one recognized
// filename across two, for no reason.
export const MediaImg: React.FC<{ src: string; style?: React.CSSProperties }> = ({ src, style }) =>
  src.endsWith(".mp4") || src.endsWith(".mov")
    ? React.createElement(Video, { src, volume: 0, style })
    : React.createElement(Img, { src, style });
