// PLACEHOLDER — regenerated by make_pkg.py from project.library.items before
// every bundle: one entry per shared-library item the user picked, keyed by
// the FULL "lib/<id>.<ext>" literal, value already a staticFile(...) call
// over that same literal. `lib/` is the one asset kind the Lana gateway
// stages ONLY from literal staticFile("lib/...") calls — the gateway never
// reads a variable reference there, so it gets its own generated manifest
// instead of resolving through project.assets like everything else. Never
// edit this file by hand.
//
// Same type-contract rule as assets-manifest.ts: make_pkg.py emits this
// exact `export const LIB_FILES: Record<string, string> = { ... };`
// annotation.
import { staticFile } from "remotion";

export const LIB_FILES: Record<string, string> = {};

void staticFile;
